### ISSUE TITLE
adding bindings to /workspace and activating CDS fail with removing the bindings host files

### ISSUE THREAD

**Issue by yhgillet** [paketo-buildpacks/spring-boot#500] opened 2024-07-24 19:42 UTC
When using the following configuration, the image build fails with error ` [creator]     Error: /workspace already exists and is not empty
` and removes the content of the /datadog host directory.
Note that when not activating the `BP_JVM_CDS_ENABLED`, it works fine.

```
<configuration>
                    <image>
                        <builder>paketobuildpacks/builder-jammy-buildpackless-tiny</builder>
                        <buildpacks>
                            <buildpack>paketobuildpacks/java</buildpack>
                        </buildpacks>
                        <bindings>
                            <!-- WARN: bindings to /workspace doesnt work and it removes your host files -->
                            <binding>${project.basedir}/datadog:/workspace/datadog</binding>
                            <!--                            <binding>${project.basedir}/datadog:/platform/bindings/datadog</binding>-->
                        </bindings>
                        <env>
                            <BP_JVM_CDS_ENABLED>true</BP_JVM_CDS_ENABLED>
                            <BP_SPRING_AOT_ENABLED>true</BP_SPRING_AOT_ENABLED>
                        </env>
                    </image>
                </configuration>
```

## Possible Solution
I found later in the docs that the recommended configuration with binding is using instead `/platform/bindings` path instead of /workspace , so maybe the buildpack should fail mentioning that the configuration is wrong.

## Steps to Reproduce

[This repo can be used to reproduce](https://github.com/yhgillet/spring-k8s)
calling `mvn clean install` shows the issue

**Comment by anthonydahanne** [comment] 2024-07-24 21:39
Hello @yhgillet , and thank you for your report.

@pivotal-david-osullivan and @dmikusa , I had a look at what @yhgillet described, and it turns out that, due to the way we unzip / rezip the workspace during CDS processing, it clashes when the user binds a volume in /workspace.

I'm not sure what's best: prevent (or discourage via warning messages) the users not to mount their bindings under workspaces, or, change the CDS processing so that it does disrupt the workspace too much.

The 
> removes the content of the /datadog host directory.

got me worried 😧  (I could reproduce everything described by @yhgillet )

**Comment by anthonydahanne** [comment] 2024-07-29 04:00
hello @yhgillet !
we have moved this issue to the `pack` cli

https://github.com/buildpacks/pack/issues/2237


I am now wondering if we also should ask @scottfrederick to get this in the Spring Boot plugins 🤔...

**Comment by anthonydahanne** [comment] 2024-10-23 02:15
closing this issue as it was solved with https://github.com/buildpacks/pack/issues/2237

**Closed by anthonydahanne** 2024-10-23 02:15 UTC
